name: TAG â†’ Script + Jenkins

on:
  push:
    tags:
      - '*'

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mostrar tag detectada
        run: |
          echo "TAG detectada:"
          git tag --points-at HEAD

      - name: Executar script bash
        run: |
          chmod +x script.sh
          ./script.sh

  trigger-jenkins:
    runs-on: ubuntu-latest
    needs: run-bash   # ðŸ‘ˆ sÃ³ roda se o script passar

    steps:
      - name: Trigger Jenkins Job
        run: |
          echo "Chamando Jenkins..."
          curl -X POST "$JENKINS_URL/job/sistema-bancario-tag-build/build" \
            --user "$JENKINS_USER:$JENKINS_TOKEN"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
